# Generated by Django 3.1.1 on 2020-09-25 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apicall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasusuario',
            name='cuenta_proveedor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Proveedor de servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentasusuario',
            name='cuenta_numero',
            field=models.CharField(max_length=50, verbose_name='Numero de Cuenta'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='institucion_id',
            field=models.CharField(max_length=5, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='institucion_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='institucion_tipo',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
    ]
