# Generated by Django 3.1.1 on 2020-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicall', '0005_auto_20200926_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='institucion_id',
            field=models.CharField(max_length=30, verbose_name='Id'),
        ),
    ]
