# Generated by Django 3.1.1 on 2020-10-06 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apicall', '0006_auto_20200928_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='procesocta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso_state', models.CharField(max_length=100, verbose_name='State')),
                ('proceso_cliente', models.CharField(max_length=100, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cuentasusuario',
            name='cuenta_Refresh_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Refresh Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentasusuario',
            name='cuenta_id_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=9999, verbose_name='Id token'),
            preserve_default=False,
        ),
    ]
