# Generated by Django 3.1.1 on 2020-10-06 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apicall', '0012_cuentasusuario_cuenta_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesocta',
            old_name='proceso_state',
            new_name='proceso_refresh_token',
        ),
        migrations.RemoveField(
            model_name='cuentasusuario',
            name='cuenta_Refresh_token',
        ),
        migrations.RemoveField(
            model_name='cuentasusuario',
            name='cuenta_token',
        ),
        migrations.RemoveField(
            model_name='procesocta',
            name='proceso_cliente',
        ),
        migrations.AddField(
            model_name='procesocta',
            name='proceso_inst_inf',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Proveedor de Informacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesocta',
            name='proceso_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=99999, verbose_name='Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesocta',
            name='proceso_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Usuario Banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentasusuario',
            name='cuenta_scope',
            field=models.CharField(max_length=999, verbose_name='Scope'),
        ),
    ]
